apiVersion: v1
kind: Service
metadata:
  name: weather-mlops-service
spec:
  type: NodePort                     # expose the service on a static port on each node
  selector:
    app: weather-mlops               # route traffic to pods with this label
  ports:
  - protocol: TCP
    port: 80                         # port the service listens on (inside the cluster)
    targetPort: 5000                 # port the container listens on
    nodePort: 30007                  # port exposed on the Minikube node IP